[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x4a2bc9c24458c4f738d88d354d868ab00abfe4e503f66476670f25c86996e96"
transaction_hash = "0x6528299c884b1b7a1b1c72c0ba7ff7430034b4fa52af099740ff00f5cf2da7a"
block_number = 3
seed = "grimscape"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/gs/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x5fb34804b83b16cd2d14908a4d69a7ad1d989adacbeb118098a306f707a5441"
class_hash = "0x5f110d055c4d9578eb9131bb39aec9631dc6c07dd2cefb40db52496a361852b"
original_class_hash = "0x5f110d055c4d9578eb9131bb39aec9631dc6c07dd2cefb40db52496a361852b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = [
    "grimscape-Player",
    "grimscape-Realm",
    "grimscape-Dungeon",
    "grimscape-Room",
    "grimscape-Adventurer",
    "grimscape-Mob",
]
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "update",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"

[[models]]
kind = "DojoModel"
class_hash = "0x5a21cdc0928b1c3aa4f48e2cebf4707bd55656ab9fa1641c25c9a8628b4b6ba"
original_class_hash = "0x5a21cdc0928b1c3aa4f48e2cebf4707bd55656ab9fa1641c25c9a8628b4b6ba"
abi = "manifests/dev/deployment/abis/models/grimscape-Adventurer-1ffbe10a.json"
tag = "grimscape-Adventurer"
qualified_path = "grimscape::models::index::adventurer"
manifest_name = "grimscape-Adventurer-1ffbe10a"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = false

[[models.members]]
name = "y"
type = "i32"
key = false

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models.members]]
name = "xp"
type = "u16"
key = false

[[models.members]]
name = "gold"
type = "u16"
key = false

[[models.members]]
name = "attribute_points"
type = "u8"
key = false

[[models.members]]
name = "attributes"
type = "u64"
key = false

[[models.members]]
name = "gears"
type = "u64"
key = false

[[models.members]]
name = "slots"
type = "u128"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xbf46d127012e9e445c5b3fcdb18ad298f6bb325625411bd26f7f707358ad88"
original_class_hash = "0xbf46d127012e9e445c5b3fcdb18ad298f6bb325625411bd26f7f707358ad88"
abi = "manifests/dev/deployment/abis/models/grimscape-AdventurerHit-5ef66a0e.json"
tag = "grimscape-AdventurerHit"
qualified_path = "grimscape::events::adventurer_hit"
manifest_name = "grimscape-AdventurerHit-5ef66a0e"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7c3362027a37f713d54c6945b6ca4d8983134a6516a2248aedd18116b23189"
original_class_hash = "0x7c3362027a37f713d54c6945b6ca4d8983134a6516a2248aedd18116b23189"
abi = "manifests/dev/deployment/abis/models/grimscape-AdventurerUpdate-3f687141.json"
tag = "grimscape-AdventurerUpdate"
qualified_path = "grimscape::events::adventurer_update"
manifest_name = "grimscape-AdventurerUpdate-3f687141"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "adventurer"
type = "Adventurer"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
original_class_hash = "0x42e27db99d48f01b5e63189bdc1d410432019af1c64a7ad50047ac3a7dc7baa"
abi = "manifests/dev/deployment/abis/models/grimscape-Dungeon-8e7b8b82.json"
tag = "grimscape-Dungeon"
qualified_path = "grimscape::models::index::dungeon"
manifest_name = "grimscape-Dungeon-8e7b8b82"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "nonce"
type = "u32"
key = false

[[models.members]]
name = "claimer"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x410ca895f3377222552c3a1ad4097e28876667d834d802e942056161f26dc57"
original_class_hash = "0x410ca895f3377222552c3a1ad4097e28876667d834d802e942056161f26dc57"
abi = "manifests/dev/deployment/abis/models/grimscape-Mob-3a6da169.json"
tag = "grimscape-Mob"
qualified_path = "grimscape::models::index::mob"
manifest_name = "grimscape-Mob-3a6da169"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "position"
type = "u8"
key = false

[[models.members]]
name = "distance"
type = "u8"
key = false

[[models.members]]
name = "next"
type = "u8"
key = false

[[models.members]]
name = "beast"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u16"
key = false

[[models.members]]
name = "level"
type = "u8"
key = false

[[models.members]]
name = "base_health"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x709ad0c320918c2908275d47605ff4dd12e20f8a553c7a3f1bdb0e6c30f2562"
original_class_hash = "0x709ad0c320918c2908275d47605ff4dd12e20f8a553c7a3f1bdb0e6c30f2562"
abi = "manifests/dev/deployment/abis/models/grimscape-MobHit-1079782b.json"
tag = "grimscape-MobHit"
qualified_path = "grimscape::events::mob_hit"
manifest_name = "grimscape-MobHit-1079782b"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "damage"
type = "u16"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4e52fceda9a41deda224052dec1e1775657a0b844fdeb6015e3197cd4d73ba1"
original_class_hash = "0x4e52fceda9a41deda224052dec1e1775657a0b844fdeb6015e3197cd4d73ba1"
abi = "manifests/dev/deployment/abis/models/grimscape-MobUpdate-3948e5b2.json"
tag = "grimscape-MobUpdate"
qualified_path = "grimscape::events::mob_update"
manifest_name = "grimscape-MobUpdate-3948e5b2"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "mob"
type = "Mob"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
original_class_hash = "0x7a942fd7613f092de3e6dc5d1d898fdc32680efc0cbb81d9304ac4a464d80bd"
abi = "manifests/dev/deployment/abis/models/grimscape-Player-560a0042.json"
tag = "grimscape-Player"
qualified_path = "grimscape::models::index::player"
manifest_name = "grimscape-Player-560a0042"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
original_class_hash = "0x76bf5653e4b6885e3e191a7f0c92020ef438f7056f60e4ebb989169968ad604"
abi = "manifests/dev/deployment/abis/models/grimscape-Realm-58d8aeac.json"
tag = "grimscape-Realm"
qualified_path = "grimscape::models::index::realm"
manifest_name = "grimscape-Realm-58d8aeac"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
original_class_hash = "0x5889d597e3889d11f43ad20a1c718e9d2fcd8ba44292f61ee54faf317a6046"
abi = "manifests/dev/deployment/abis/models/grimscape-Room-58989322.json"
tag = "grimscape-Room"
qualified_path = "grimscape::models::index::room"
manifest_name = "grimscape-Room-58989322"

[[models.members]]
name = "realm_id"
type = "u32"
key = true

[[models.members]]
name = "dungeon_id"
type = "u32"
key = true

[[models.members]]
name = "adventurer_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "i32"
key = true

[[models.members]]
name = "y"
type = "i32"
key = true

[[models.members]]
name = "width"
type = "u8"
key = false

[[models.members]]
name = "height"
type = "u8"
key = false

[[models.members]]
name = "mob_count"
type = "u8"
key = false

[[models.members]]
name = "entities"
type = "felt252"
key = false

[[models.members]]
name = "grid"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false
