kind = "DojoModel"
class_hash = "0x6531637b0bbd741f8823b127d8958ed10a483dd1f2d7654975c1d7d7cbdab65"
original_class_hash = "0x6531637b0bbd741f8823b127d8958ed10a483dd1f2d7654975c1d7d7cbdab65"
abi = "manifests/dev/base/abis/models/grim_defiance-Position-2ac8b4c1.json"
tag = "grim_defiance-Position"
qualified_path = "grim_defiance::models::position"
manifest_name = "grim_defiance-Position-2ac8b4c1"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
