kind = "DojoContract"
class_hash = "0x5f110d055c4d9578eb9131bb39aec9631dc6c07dd2cefb40db52496a361852b"
original_class_hash = "0x5f110d055c4d9578eb9131bb39aec9631dc6c07dd2cefb40db52496a361852b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-Actions-70c595b8.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-Actions"
systems = [
    "signup",
    "rename",
    "create",
    "update",
    "multiperform",
]
manifest_name = "grimscape-Actions-70c595b8"
